#! /bin/sh
### Fonts
xset +fp /home/juki/.fonts
xset +fp /home/juki/.local/share/fonts
xset fp rehash

test -r ~/github/nord-dircolors/src/dir_colors && eval $(dircolors ~/github/nord-dircolors/src/dir_colors)

### Polybar
killall -q polybar
pkill polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
pgrep -x polybar > /dev/null || polybar example &

### Autostart
pgrep -x sxhkd > /dev/null || sxhkd & #Keybindings
tlp start #Batterysaver
compton & #Compositor
nm-applet & #Networkmanager applet

killall -q redshift
pkill redshift
redshift & #Orangescreen

### Wallpaper
#nitrogen --set-auto /home/juki/.wallpapers/pink-nord-theme/cyberpunk-sword.png
#nitrogen --set-auto /home/juki/.wallpapers/pink-nord-theme/cyberpunk-sword.png
nitrogen --set-zoom-fill /home/juki/.wallpapers/simp_pekora_2.2.jpg

### BSPC
#bspc monitor -d 一 二 三 四 五 六 七 八 九 十
bspc monitor -d 一 二 三 四 五

bspc config automatic_scheme longest_side
bspc config initial_polarity second_child

## Mouse
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false

## Other
bspc config focused_border_color "#daa6ca"
bspc config normal_border_color "#332d29"
bspc config active_border_color "#817267"
bspc config presel_border_color "#9a875f"
bspc config urgent_border_color "#9f7155"
bspc config focused_locked_border_color "#9a875f"

bspc config border_width         2
bspc config window_gap           7
bspc config top_padding          34

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^2' state=floating follow=on
bspc rule -a Screenkey manage=off
bspc rule -a Thunar pseudo_tiled=on
#bspc rule -a Chromium desktop='^2'
